Repository bitia-ru/gekkon-frontend, pull requests merged in 2020-12, with the labels that each got.

#278 GF-277: Разбить фильтр 6В-7А+ на два: 6В-6С+ и 6С-7А+
  src/v1/Constants/Categories.js
  src/v1/components/FilterBlock/FilterBlock.js
  src/v1/utils/getCategoryId.js
Labels: enhancement

#280 GF-279: Добавить фильтр "Период -> Две недели" и "Год" заменить на "2 месяца"
  src/v1/Constants/PeriodFilters.js
  src/v2/utils/reloadRoutes.js
Labels: enhancement

#287 GF-286: Sort spots by activity (stage 2)
  src/v2/components/spots/SpotsBlock/SpotsBlock.jsx
Labels: feature

#290 Release/0.17.0
  src/v2/components/spots/SpotsBlock/SpotsBlock.jsx
Labels: release

#292 GF-291: Temporary fix UserPoster error
  src/v2/components/UserPoster/UserPoster.js
Labels: bug

#293 Release/0.17.1
  src/v2/components/UserPoster/UserPoster.js
Labels: hotfix

#295 GF-294: Add mark colors for scheme pointer
  src/v2/components/Scheme/Scheme.js
  src/v2/components/SchemePointer/SchemePointer.js
Labels: feature

#296 GF-294: Add mark colors for scheme pointer
  src/v2/components/Scheme/Scheme.js
  src/v2/components/SchemePointer/SchemePointer.js
Labels: hotfix
