Repository bitia-ru/gekkon-frontend, pull requests merged in 2020-09, with the labels that each got.

#90 GKN-207: Миграция стилей на aphrodite: UserIcon
  src/v2/components/UserIcon/UserIcon.css
  src/v2/components/UserIcon/UserIcon.js
Labels: feature

#189 GF-188: При запросе списка трасс не запрашивать пролазы
  src/v2/components/RouteCard/RouteCard.js
  src/v2/components/RouteStatus/RouteStatus.js
  src/v2/redux/routes/actions.js
  src/v2/redux/routes/reducer.js
Labels: enhancement

#192 GF-191: Некорректное отображение ошибки при логине, если пароль не установлен
  src/v2/utils/auth.js
Labels: bug

#201 GF-200: В Firefox уезжает разметка трассы
  src/v1/components/RouteEditor/RouteEditor.css
  src/v2/components/RouteEditor/RouteEditor.js
  src/v2/components/RoutesEditModal/RoutesEditModal.js
  src/v2/components/RoutesShowModal/RoutesShowModal.js
Labels: bug

#210 GF-204: В Firefox окно для кропа фото не подгоняется под размер экрана
  src/v1/components/RoutePhotoCropper/RoutePhotoCropper.js
  src/v1/components/RoutePhotoCropper/styles.js
Labels: bug

#209 GF-205: В Firefox съезжает отображение маркеров при редактировании
  src/v2/components/Marker/Marker.js
Labels: bug

#212 GF-211: Fix marker position for different screen size (firefox)
  src/v2/components/RoutesEditModal/RoutesEditModal.js
Labels: bug

#217 GF-214: Дефолтное значение даты на схеме зала сделать «не задано»
  src/v1/Constants/DefaultFilters.js
Labels: bug

#227 GF-226: Незалогиненному юзеру показывают фильтр «Понравившиеся мне»
  src/v1/components/FilterBlock/FilterBlock.js
Labels: bug

#221 GF-220: Клавиши вправо-влево на трассе мешают написанию комментария
  src/v1/components/CommentForm/CommentForm.js
Labels: bug

#219 GF-218: Переделать загрузку фото трасс
  package-lock.json
  package.json
  src/v1/Workarounds/EXIFRotateIgnored.js
  src/v1/components/RoutePhotoCropper/RoutePhotoCropper.js
  src/v1/components/RoutesEditModal/RoutesEditModal.css
  src/v1/components/RoutesEditModal/RoutesEditModal.js
  src/v2/components/RoutesEditModal/RoutesEditModal.js
  src/v2/redux/wall_photos/actions.js
  src/v2/redux/wall_photos/reducer.js
Labels: enhancement
