Repository bitia-ru/gekkon-frontend, pull requests merged in 2020-11, with the labels that each got.

#266 GF-265: Не работает автоматическое проставление категории по цвету маркировки
  src/v2/components/RouteDataEditableTable/RouteDataEditableTable.js
Labels: bug

#268 GF-265: Fix auto category select
  src/v2/components/RouteDataEditableTable/RouteDataEditableTable.js
Labels: hotfix

#255 GF-245: Брать дату пролаза при добавлении пролаза из даты в фильтрах на схеме зала
  src/v2/forms/RouteAscents/RouteAscents.jsx
Labels: enhancement

#269 Release 0.14.2
  src/v2/forms/RouteAscents/RouteAscents.jsx
Labels: hotfix

#273 GF-272: Sort spots by activity
  src/v2/components/spots/SpotsBlock/SpotsBlock.jsx
Labels: feature

#276 GF-275: Автопроставление даты накрутки
  src/v2/components/RoutesEditModal/RoutesEditModal.js
Labels: enhancement

#281 Release/0.15.0
  src/v2/components/RoutesEditModal/RoutesEditModal.js
Labels: release
