Repository bitia-ru/gekkon-frontend, pull requests merged in 2021-03, with the labels that each got.

#314 Release/0.19.1
  docker/configs/nginx.conf
Labels: release

#318 GF-317: Изменить сообщение о невалидном логине
  src/v2/forms/Profile/Profile.js
Labels: enhancement

#316 GF-315: Загрузка и обновление фотографии трассы через drag-n-drop фотографии и copy/paste
  src/v2/components/RoutesEditModal/RoutesEditModal.js
Labels: feature

#321 GF-320: При открытии профиля автозаполняется пароль
  src/v1/components/FormField/FormField.js
  src/v2/forms/Profile/Profile.js
Labels: bug

#323 GF-322: Moving karma from data to dedicated field
  src/v2/components/UserPoster/UserPoster.js
  src/v2/screens/Users.jsx
Labels: feature
